// Code generated by "esc -private -local-prefix-cwd -pkg=main -o=resources.go template/"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(path.Join("/Users/martin/go/src/github.com/programmfabrik/errorgen", f.local))
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/template/codegen.go.tmpl": {
		name:    "codegen.go.tmpl",
		local:   "template/codegen.go.tmpl",
		size:    3143,
		modtime: 1603369091,
		compressed: `
H4sIAAAAAAAC/5xWS2/jNhA+V79iqmYXVJBS9wV8aJvtoofuGnW2PbQFlpZGDhGbUinKiSHovxccPiTZ
ivvIJSY5j2++eakRxZPYIfQ98Hu+9qdhSBJ5aGptgCUAaXUwqf2/PRls6ZfBF5MbPDR7YZBuWqOl2rlX
3SkjD5iXuO129qbvvwUt1A7hxtt9t4Ibfs9/cqdhsGpWKrwPQ9BDVdr3LEnyHD4dUT9raRDMo2zB1CBV
se9KhACG/9ip4mfRgFSmBvOIoFGVaMElR6FtpNbxWmMlX2AYHryeVWsvrCSJOTV4ofRe61p/QGWdoK5E
gdAnAHTNMnBcJF99Vs9aNCwDtA8JwFpocWhZNur1A+Q5/IKm06qFht6ha7GEqtYT6N74D3WJ0YHV/CgO
CDkUdYlQVxRvcLYxonhiGfz+p83b1E1rX+biQ5L0fchRiZW1ewc3qLXDHBJ2j5Xo9qZ1KcvzC2rs2es7
mUUC51ITOhIAeJXu8OhhNsqBJNYI4AiXXNu/D2isOZKFYWAZWScV/jCKbc7E5kJZ8OyLEWBIxtOEOdT6
jiILfBH062yh1u6dDlax0VKZCtI37Zs2nSqcyW7mwuQrtTYsqAnzuLEkt0Z3hQFHcSM0KhNrBULpOQzD
4GikF1ctrooo8pnpKDu3P8mSI2RNjJRY8fMMUds3FqGvijVxDl/i8TsYhi+BPrq5D+rznIwkU1lpX+8C
FD6DVK0RqqA+iSLP0jxC6YoajmLfoQ266lQRZVgGtyOLLjxK09t42zswyB1XK6DJx30H/ndCQFY+0F/H
a2s/cmULNGb+m2M6Ec9GM5Ga85NjBmI+KWA2qZZsYdz0U9UL/7E0XzHoZivLgN3GKRuG750rxGzuIop9
xGeWqjTjPjKa1ezqJI+ya6FbZH478QctD4vU8U8wDHeQwh8qzbIrUZxN1Rlgn/8r2vMN4bUNhW/LAbkn
ie5lRfdfr0DJvZe1japkwaqD4RsXBUvJKhT1oZF7azYQ9w7e/JWS8cxZdMnfdjSeaJvz77uqQh0KWGtY
geHvX7DoDLK32666A+Rhb/0vXEjG/gUuz+K2q/iG+GExEWP3POHpev/keZj5T3iaTgG77KjDw+Z7whNp
LORpZoFl88EUIo5Zd7OTjxqToPI87BYPp0Xzz1BupxU3w3KcT8ksolmAASs4zqHMcUw5EaqczMuibk6z
DwRgXYv0TVI8Cqmk2mWvAr6G9mKSXgc+m1QujsnepZB89iP2/d7tMjSoWxAtHESz2IyLH2Nn/dyENRi8
/aZFAzt5RBV35xIFVozZJvFz7SJs20PcL+HFRko/K7Hdo/3EtR+R0Pc3GPaV2GsU5QnwRbbUWM4QT6fd
FM2vLIirU3+KfP7NusAHKuP0J4n4OwAA///P99aMRwwAAA==
`,
	},

	"/template": {
		name:  "template",
		local: `template/`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"template/": {
		_escData["/template/codegen.go.tmpl"],
	},
}
